apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-influxdb
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: influxdb
    spec:
      containers:
      - name: influxdb
        image: gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1
        command: ["influxd","--config","/etc/influxdb/config.toml"]
        ports:
        - name: admin
          containerPort: 8083
        - name: data
          containerPort: 8086
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
        - mountPath: /etc/influxdb
          name: influxdb-conf
      volumes:
      - name: influxdb-storage
        persistentVolumeClaim:
         claimName: monitorin-influxdb-pvc
      - name: influxdb-conf
        configMap:
           name:  influxdb-conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-influxdb
  name: monitoring-influxdb
  namespace: monitoring
spec:
  ports:
  - name: data
    port: 8086
    targetPort: 8086
  - name: admin
    port: 8083
    targetPort: 8083
  selector:
    k8s-app: influxdb