kind: Namespace
apiVersion: v1
metadata:
  name: monitoring
  annotations:
    net.beta.kubernetes.io/network-policy: |
      {
        "ingress": {
          "isolation": "DefaultDeny"
        }
      }
